//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloud_persons_images
    {
        public string img_name { get; set; }
        public byte[] Person_img { get; set; }
        public string Img_ext { get; set; }
        public System.DateTime Createdtime { get; set; }
    }
}
