//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_PERSONSTATUS
    {
        public string person_id { get; set; }
        public decimal tagid { get; set; }
        public decimal zone_id { get; set; }
        public decimal status { get; set; }
        public System.DateTime stime { get; set; }
        public System.DateTime created_time { get; set; }
    
        public virtual RTLS_PERSONDTLS RTLS_PERSONDTLS { get; set; }
    }
}
