//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_SMS_TRANSACTIONS
    {
        public string SMS_ID { get; set; }
        public string person_id { get; set; }
        public decimal tagid { get; set; }
        public decimal fltno { get; set; }
        public string username { get; set; }
        public string sender_id { get; set; }
        public string provider { get; set; }
        public string REC_MOBILENO { get; set; }
        public string MSG { get; set; }
        public Nullable<decimal> sent_notsent { get; set; }
        public Nullable<System.DateTime> SENT_TIME { get; set; }
        public Nullable<System.DateTime> GeneratedTime { get; set; }
        public string DELIVERY_STATUS { get; set; }
        public Nullable<System.DateTime> DELIVERED_TIME { get; set; }
    }
}
