//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_RESCUE_TEAM_MEMBERS
    {
        public string member_id { get; set; }
        public string memeber_name { get; set; }
        public string mobile_no { get; set; }
        public string alt_mobile_no { get; set; }
        public System.DateTime created_time { get; set; }
        public decimal actinact { get; set; }
        public decimal opeartion_type { get; set; }
    }
}
