//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_DESIGNATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTLS_DESIGNATIONS()
        {
            this.RTLS_PERSONDTLS = new HashSet<RTLS_PERSONDTLS>();
        }
    
        public decimal desg_id { get; set; }
        public string desg_name { get; set; }
        public decimal actinact { get; set; }
        public System.DateTime created_time { get; set; }
        public decimal opeartion_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTLS_PERSONDTLS> RTLS_PERSONDTLS { get; set; }
    }
}
