//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_PERTRK_CONFIG
    {
        public decimal ALM_WTTIME { get; set; }
        public decimal ALLWELL_WTTME { get; set; }
        public decimal alm_sent_cnt { get; set; }
        public decimal OUT_allowedtime { get; set; }
        public decimal inactallowedtime { get; set; }
        public decimal TEMPMIN { get; set; }
        public decimal TEMPMAX { get; set; }
        public decimal LOW_BATTERY_PERCENT { get; set; }
        public decimal MaxTAGIDNum { get; set; }
        public decimal MaxBSIDNum { get; set; }
        public byte[] created_time { get; set; }
    }
}
