//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_Zone_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTLS_Zone_Category()
        {
            this.RTLS_ZONEDTLS = new HashSet<RTLS_ZONEDTLS>();
        }
    
        public string ZCAT_NAME { get; set; }
        public decimal ZCAT_NO { get; set; }
        public decimal operation_type { get; set; }
        public System.DateTime CREATEDTIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTLS_ZONEDTLS> RTLS_ZONEDTLS { get; set; }
    }
}
