//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_LOGINS
    {
        public decimal SID { get; set; }
        public decimal LOG_TYPE { get; set; }
        public string USER_ID { get; set; }
        public string PASSWORD { get; set; }
        public decimal ACTINACT { get; set; }
    }
}
