//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_FAULT_DTLS
    {
        public Nullable<decimal> ZONE_ID { get; set; }
        public Nullable<decimal> faultno { get; set; }
        public string fltname { get; set; }
        public string FLTINFO { get; set; }
        public string PERSON_ID { get; set; }
        public Nullable<decimal> TAG_ID { get; set; }
        public Nullable<decimal> DLTIME { get; set; }
        public Nullable<decimal> DLYEAR { get; set; }
        public Nullable<System.DateTime> ORC_DATETIME { get; set; }
        public Nullable<decimal> CLEARED_TIME { get; set; }
        public Nullable<decimal> CLEAREDYEAR { get; set; }
        public Nullable<System.DateTime> CLEARED_DATETIME { get; set; }
        public string FAULTLEVEL { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
    }
}
