//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tata_rakshak : DbContext
    {
        public tata_rakshak()
            : base("name=tata_rakshak")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cloud_persons_images> Cloud_persons_images { get; set; }
        public virtual DbSet<RTLS_DEPARTMENTS> RTLS_DEPARTMENTS { get; set; }
        public virtual DbSet<RTLS_DESIGNATIONS> RTLS_DESIGNATIONS { get; set; }
        public virtual DbSet<RTLS_GATEWAY> RTLS_GATEWAY { get; set; }
        public virtual DbSet<RTLS_LOGINS> RTLS_LOGINS { get; set; }
        public virtual DbSet<RTLS_ONLINEPERSONSTATUS> RTLS_ONLINEPERSONSTATUS { get; set; }
        public virtual DbSet<RTLS_PERSONDTLS> RTLS_PERSONDTLS { get; set; }
        public virtual DbSet<RTLS_PERSONSIMEIDATA> RTLS_PERSONSIMEIDATA { get; set; }
        public virtual DbSet<RTLS_PERSONSTATUS> RTLS_PERSONSTATUS { get; set; }
        public virtual DbSet<RTLS_PERTRKFAULTINFO> RTLS_PERTRKFAULTINFO { get; set; }
        public virtual DbSet<RTLS_RESCUE_TEAM_MEMBERS> RTLS_RESCUE_TEAM_MEMBERS { get; set; }
        public virtual DbSet<RTLS_SMS_TRANSACTIONS> RTLS_SMS_TRANSACTIONS { get; set; }
        public virtual DbSet<RTLS_STATUSES> RTLS_STATUSES { get; set; }
        public virtual DbSet<RTLS_TAG_ZONE_CONFIG> RTLS_TAG_ZONE_CONFIG { get; set; }
        public virtual DbSet<RTLS_Zone_Category> RTLS_Zone_Category { get; set; }
        public virtual DbSet<RTLS_ZONEDTLS> RTLS_ZONEDTLS { get; set; }
        public virtual DbSet<RTLS_FAULT_DTLS> RTLS_FAULT_DTLS { get; set; }
        public virtual DbSet<RTLS_PERSONSTATUS_HISTORY> RTLS_PERSONSTATUS_HISTORY { get; set; }
        public virtual DbSet<RTLS_PERTRK_CONFIG> RTLS_PERTRK_CONFIG { get; set; }
        public virtual DbSet<RTLS_SYNC_DTLS> RTLS_SYNC_DTLS { get; set; }
        public virtual DbSet<RTLS_SpotLevelMap> RTLS_SpotLevelMap { get; set; }
    }
}
