//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_ZONEDTLS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RTLS_ZONEDTLS()
        {
            this.RTLS_TAG_ZONE_CONFIG = new HashSet<RTLS_TAG_ZONE_CONFIG>();
        }
    
        public decimal gid { get; set; }
        public decimal zone_id { get; set; }
        public string zone_name { get; set; }
        public string area { get; set; }
        public decimal safe_unsafe { get; set; }
        public Nullable<decimal> BS_SIGNALSTRENGTH { get; set; }
        public Nullable<decimal> BS_BATTERY_STATUS_VAL { get; set; }
        public Nullable<decimal> BS_BATTERY_STATUS_PERCNT { get; set; }
        public Nullable<System.DateTime> POWERON { get; set; }
        public Nullable<decimal> actinact { get; set; }
        public System.DateTime created_time { get; set; }
        public decimal oparation_type { get; set; }
    
        public virtual RTLS_GATEWAY RTLS_GATEWAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTLS_TAG_ZONE_CONFIG> RTLS_TAG_ZONE_CONFIG { get; set; }
        public virtual RTLS_Zone_Category RTLS_Zone_Category { get; set; }
    }
}
