//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTLSWebService.Models.RTLS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLS_PERSONDTLS
    {
        public string PERSON_ID { get; set; }
        public Nullable<decimal> TAG_ID { get; set; }
        public string PERSONNAME { get; set; }
        public decimal DEPARTMENT_id { get; set; }
        public decimal DESIGNATION_id { get; set; }
        public string MOBILE_NO { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public Nullable<System.DateTime> Assigned_time { get; set; }
        public Nullable<System.DateTime> Un_Assigned_time { get; set; }
        public decimal ACTINACT { get; set; }
        public decimal OPERATION_TYPE { get; set; }
        public int Tagtransact_type { get; set; }
    
        public virtual RTLS_DEPARTMENTS RTLS_DEPARTMENTS { get; set; }
        public virtual RTLS_DESIGNATIONS RTLS_DESIGNATIONS { get; set; }
        public virtual RTLS_ONLINEPERSONSTATUS RTLS_ONLINEPERSONSTATUS { get; set; }
        public virtual RTLS_PERSONSTATUS RTLS_PERSONSTATUS { get; set; }
    }
}
